apiVersion: v2
name: kafka-ui
description: |
  This chart installs kafka-ui
version: "0"
dependencies:
  - name: kafka-ui
    repository: https://provectus.github.io/kafka-ui-charts
    version: "0.7.6"
